### ISSUE TITLE
Figure 3c,d,e Notebook fails without precomputed models

### ISSUE THREAD

**Issue by kienerj** [dream-olfaction/olfaction-prediction#9]
The [Figure 3c,d,e notebook](https://github.com/dream-olfaction/olfaction-prediction/blob/dev/opc_python/paper/fig3cde-CorrelationVsNumFeatures.ipynb) fails in cell 4 "Load or compute the random forest model" in the else-block if `use_saved_rf_model = False`. It has to be set to `False` because the repository does not contain these saved models.

```python
else:	
	trans_params = params.get_trans_params(Y_all, descriptors, plot=False)
    use_et, max_features, max_depth, min_samples_leaf, trans_weight, regularize, use_mask = params.get_other_params()
    rs_forest = fit2.feature_sweep(X_drag_morg[:,:-1],Y,n_estimators=50,n_splits=n_splits,n_features=n_features,model='rf',
                              rfe=False,max_features=max_features,max_depth=max_depth,min_samples_leaf=min_samples_leaf)
    np.save('../../data/rs_forest_%d',rs_forest)
```
`NameError: name 'Y_all' is not defined`

If `Y_all` is replaced with `Y` defined in cell 3, then you get another issue due to missing imports:

`NameError: name 'fit2' is not defined`

If you then import the missing module:

`from gerkin import fit2` another undefined error is thrown:

`NameError: name 'X_drag_morg' is not defined`

At that point I gave up to try to fix it. This issue could be solved by supplying the underlying precomputed results in the repository or by fixing the else-block.

(Note: Applies to master and dev branch)

**Comment by rgerkin** [comment]
@kienerj 
I see.  I'll take a look this week.

**Comment by rgerkin** [comment]
@kienerj 
When I changed the API a few months ago to use Pandas I forgot to update the code blocks that actually regenerate the model (as opposed to just checking the paper figures against it).  I will fix in the coming week.

**Comment by rgerkin** [comment]
@kienerj 
I've fixed that notebook and the associated files to run with the new API, computing models as they go.  I've successfully tested it (but using a smaller number of cross-validation splits for speed).  Let me know if you have any trouble.  

I only applied this fix to the dev branch, so you will want to work with that code until I have a chance to check how this affects every other notebook.
